version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    user: root
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - BROKER_ID=1
     - LOG_DIRS=/kafka/kafka-logs-1
     - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
     - KAFKA_DEFAULT_REPLICATION_FACTOR=2


  kafka-2:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    user: root
    ports:
      - 9093:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - BROKER_ID=2
      - LOG_DIRS=/kafka/kafka-logs-2
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2

  mysql:
    image: debezium/example-mysql:${DEBEZIUM_VERSION}
    ports:
     - 3307:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
#  elastic:
#    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
#    ports:
#     - "9200:9200"
#    environment:
#     - http.host=0.0.0.0
#     - transport.host=127.0.0.1
#     - xpack.security.enabled=false
#     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  connect:
    image: debezium/connect-jdbc-es:${DEBEZIUM_VERSION}
    build:
      context: debezium-jdbc-es
    ports:
     - 8083:8083
     - 5005:5005
    links:
     - kafka
     - kafka-2
     - mysql
#     - elastic
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092,  kafka-2:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
